name: Build and Deploy EXE

on:
  push:
    branches:
      - main  # Trigger on pushes to the main branch
  workflow_dispatch:  # Allow manual trigger of the workflow

jobs:
  build:
    runs-on: windows-latest  # Use a Windows runner to build the EXE

    steps:
    - name: Checkout code
      uses: actions/checkout@v3  # Check out the repository code

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'  # Set Python version (compatible with cx_Freeze)

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install cx_Freeze

    - name: Build EXE
      run: |
        python setup.py build  # Use setup.py to build the executable
        dir  # List files to verify output location

    - name: Upload EXE Artifact
      uses: actions/upload-artifact@v3
      with:
        name: exe-build
        path: build/exe.win-amd64-3.10/  # Adjust this path if needed

